version: '2'

volumes:
  influxdb-data:
  dashboard-data:

services:
  handheld:
    build: ./handheld
    restart: always
    privileged: true
    network_mode: host
    devices:
      - /dev/snd:/dev/snd

  # mqtt:
  #   image: eclipse-mosquitto:1.6.15
  #   restart: always
  #   privileged: false
  #   ports:
  #     - '1883:1883'

  # connector:
  #   image: balenablocks/connector:latest
  #   restart: always
  #   privileged: true
  #   labels:
  #     io.balena.features.balena-api: '1' # necessary to discover services
  #     io.balena.features.supervisor-api: '1' # necessary to discover services in local mode

  # influxdb:
  #   image: arm32v7/influxdb@sha256:2fed9b09a672cab330ac3ea1f03616e6821f2235bda64d549f605ef0d7081911
  #   restart: always
  #   privileged: false
  #   volumes:
  #     - 'influxdb-data:/var/lib/influxdb'

  # dashboard:
  #   image: balenablocks/dashboard
  #   restart: always
  #   privileged: false
  #   volumes:
  #     - 'dashboard-data:/data'
  #   ports:
  #     - '80'
