version: '2'

volumes:
  influxdb-data: null
  dashboard-data: null
  pulseaudio_unix_socket: null # shared volume where pulseaudio unix socket will be stored.
  pulse: null
  ble-emitter-data: null

networks:
  zimnocieplo: null

services:
  # zinocieplo:
  #   build: ./zimnocieplo
  #   restart: always
  #   privileged: true
  #   environment:
#     - PULSE_SERVER=tcp:audio:4317
  #   depends_on:
  #     - audio
  #     - bluetooth
  #   networks:
  #     - zimnocieplo

  ble_emitter:
    build: ./ble-emitter
    network_mode: host
    restart: on_failure
    privileged: true
    cap_add:
      - NET_ADMIN
    volumes:
      - ble-emitter-data:/var/ble-emitter

  bluetooth:
    image: tmigone/bluetooth:raspberrypi0-2w-64
    network_mode: host
    cap_add:
      - NET_ADMIN
    restart: on-failure
    labels:
      io.balena.features.dbus: 1
    environment:
      - BLUETOOTH_CONNECT_DEVICE=50:C2:ED:96:90:AF

  audio:
    image: balenablocks/audio
    privileged: true
    labels:
      io.balena.features.dbus: 1 # Only required for bluetooth support
    networks:
      - zimnocieplo

  mqtt:
    image: eclipse-mosquitto
    restart: always
    ports:
      - '1883:1883'
    networks:
      - zimnocieplo
  
      # connector:
  #   image: balenablocks/connector:latest
  #   restart: always
  #   privileged: true
  #   labels:
  #     io.balena.features.balena-api: '1' # necessary to discover services
  #     io.balena.features.supervisor-api: '1' # necessary to discover services in local mode

  # influxdb:
  #   image: arm32v7/influxdb@sha256:2fed9b09a672cab330ac3ea1f03616e6821f2235bda64d549f605ef0d7081911
  #   restart: always
  #   privileged: false
  #   volumes:
  #     - 'influxdb-data:/var/lib/influxdb'

  # dashboard:
  #   image: balenablocks/dashboard
  #   restart: always
  #   privileged: false
  #   volumes:
  #     - 'dashboard-data:/data'
  #   ports:
  #     - '80'
