version: '2'

volumes:
  influxdb-data:
  dashboard-data:
  pulseaudio_unix_socket:  # shared volume where pulseaudio unix socket will be stored.
  pulse:

networks:
  zimnocieplo:
  
services:
  zinocieplo:
    build: ./zimnocieplo
    restart: always
    privileged: true
    environment:
      - PULSE_SERVER=tcp:audio:4317
    depends_on:
      - audio
      - bluetooth
    cap_add:
      - NET_ADMIN
    networks:
      - zimnocieplo
    
  bluetooth:
    image: tmigone/bluetooth:raspberrypi0-2w-64
    network_mode: host
    cap_add:
      - NET_ADMIN
    restart: on-failure
    labels:
      io.balena.features.dbus: 1
    environment:
      - BLUETOOTH_CONNECT_DEVICE=50:C2:ED:96:90:AF
  
  audio:
    image: balenablocks/audio
    privileged: true
    labels:
      io.balena.features.dbus: 1  # Only required for bluetooth support
    ports:
      - 4317:4317                 # Only required if using PA over TCP socket
    volumes:
      - 'pulse:/run/pulse'
    networks:
      - zimnocieplo
  
  # mqtt:
  #   image: eclipse-mosquitto:1.6.15
  #   restart: always
  #   privileged: false
  #   ports:
  #     - '1883:1883'

  # connector:
  #   image: balenablocks/connector:latest
  #   restart: always
  #   privileged: true
  #   labels:
  #     io.balena.features.balena-api: '1' # necessary to discover services
  #     io.balena.features.supervisor-api: '1' # necessary to discover services in local mode

  # influxdb:
  #   image: arm32v7/influxdb@sha256:2fed9b09a672cab330ac3ea1f03616e6821f2235bda64d549f605ef0d7081911
  #   restart: always
  #   privileged: false
  #   volumes:
  #     - 'influxdb-data:/var/lib/influxdb'

  # dashboard:
  #   image: balenablocks/dashboard
  #   restart: always
  #   privileged: false
  #   volumes:
  #     - 'dashboard-data:/data'
  #   ports:
  #     - '80'
