version: '2'

volumes:
  influxdb-data: null
  dashboard-data: null
  pulseaudio_unix_socket: null # shared volume where pulseaudio unix socket will be stored.
  pulse: null
  ble-emitter-data: null

networks:
  zimnocieplo: null

services:
  zinocieplo:
    build: ./zimnocieplo
    restart: always
    privileged: true
    depends_on:
      - audio
      - bluetooth
    networks:
      - zimnocieplo
    volumes:
      - 'pulse:/run/pulse'

  ble_emitter:
    build: ./ble-emitter
    network_mode: host
    restart: on_failure
    depends_on:
      - mqtt
    privileged: true
    cap_add:
      - NET_ADMIN
    volumes:
      - ble-emitter-data:/var/ble-emitter
    environment:
      - BEACON_UUID=4945d64b-57aa-cdb8-8b48-c487a2163f86

  bluetooth:
    image: tmigone/bluetooth:raspberrypi0-2w-64
    network_mode: host
    cap_add:
      - NET_ADMIN
    restart: on-failure
    labels:
      io.balena.features.dbus: 1
    environment:
      - BLUETOOTH_CONNECT_DEVICE=50:C2:ED:96:90:AF

  audio:
    image: balenablocks/audio
    privileged: true
    labels:
      io.balena.features.dbus: 1 # Only required for bluetooth support
    volumes:
      - 'pulse:/run/pulse'

  mqtt:
    image: eclipse-mosquitto:1.6.15
    restart: always
    networks:
      - zimnocieplo
    ports:
      - '1883:1883'
