version: '2'

volumes:
  influxdb-data:
  dashboard-data:
  pulseaudio_unix_socket:  # shared volume where pulseaudio unix socket will be stored.
  
services:
  handheld:
    build: ./handheld
    restart: always
    privileged: true
    network_mode: host
    environment:
      - PULSE_SERVER=tcp:localhost:4713
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
    depends_on:
      - pulseaudio-server
    cap_add:
      - NET_ADMIN
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.kernel-modules: '1'

  pulseaudio-server:
    build: ./pulseaudio-server
    restart: always
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.kernel-modules: '1'
    devices:
      - "/dev/snd:/dev/snd/"
      - "/dev/bus/usb:/dev/bus/usb"
    cap_add:
      - NET_ADMIN
    ports:
      - "4713:4713"
    volumes:
      - 'pulseaudio_unix_socket:/pulseaudio' # folder where pulseAudio unix socket is created.
      - bluetooth_device_address: 50:C2:ED:96:90:AF
    environment:
      - UDEV=1
      - PGID=1000
      - PUID=1000
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
  
  # mqtt:
  #   image: eclipse-mosquitto:1.6.15
  #   restart: always
  #   privileged: false
  #   ports:
  #     - '1883:1883'

  # connector:
  #   image: balenablocks/connector:latest
  #   restart: always
  #   privileged: true
  #   labels:
  #     io.balena.features.balena-api: '1' # necessary to discover services
  #     io.balena.features.supervisor-api: '1' # necessary to discover services in local mode

  # influxdb:
  #   image: arm32v7/influxdb@sha256:2fed9b09a672cab330ac3ea1f03616e6821f2235bda64d549f605ef0d7081911
  #   restart: always
  #   privileged: false
  #   volumes:
  #     - 'influxdb-data:/var/lib/influxdb'

  # dashboard:
  #   image: balenablocks/dashboard
  #   restart: always
  #   privileged: false
  #   volumes:
  #     - 'dashboard-data:/data'
  #   ports:
  #     - '80'
