FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine-node

RUN install_packages bluez-deprecated bluez-btmon

WORKDIR /app

RUN install_packages

COPY package*.json ./

COPY tsconfig.json ./

RUN JOBS=MAX npm install --unsafe-perm && npm cache verify && rm -rf /tmp/*

COPY src ./

RUN npm run build

COPY start.sh ./

COPY ibeacon_scan ./

COPY package.json ./

RUN chmod +x ibeacon_scan

RUN chmod +x start.sh

CMD [ "/app/start.sh"]
