FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine-node

WORKDIR /app 

RUN install_packages alsa-plugins-pulse sox

COPY audio ./audio

COPY start.sh ./

COPY package*.json ./

COPY tsconfig.json ./

COPY src ./

RUN JOBS=MAX npm install --unsafe-perm && npm cache verify && rm -rf /tmp/*

RUN npm run build

RUN chmod +x start.sh

CMD [ "/app/start.sh"]
